# Function to return Dataframe from a HDF file

In [9]:
def hdf_to_dataframe(hdf_file_path,year,csv):
    try:
        import pandas as pd 
        import h5py
        import numpy as np
        import os
        import tables
    except:
        print("Missing Library")
    year = str(year)
    file_n = hdf_file_path.split('.')
    Name = file_n[1]
    A = h5py.File(hdf_file_path, 'r')
    list_1 = list(A.keys())
    list_df = pd.DataFrame()
    list_df2 = pd.DataFrame()
    list_df["keys"] = list_1
    lat = A['lat']   
    lon = A['lon'] 
    data_pd = pd.DataFrame()   
    list_df2["keys"] = list_df["keys"].loc[0:37]
    count = 0
    for keys in list_df2["keys"]:
          if keys == 'ACond_tavg':
              data_arr = A[keys][0,:,:]
              data_pd = pd.DataFrame(data = data_arr)
              data_pd.columns = lon
              data_pd.index = lat
              col_n = year + keys
              data_pd = pd.melt(data_pd, ignore_index = False, var_name='lon', value_name= col_n)
              print(keys)
          else:
              data_arr = A[keys][0,:,:]
              data = pd.DataFrame(data = data_arr)
              data.index = lat
              col_n = year + keys
              data = pd.melt(data, ignore_index = False, value_name= col_n)
              data_pd[col_n] = data.loc[:,col_n]
    if csv == 1:
          data_pd['lat'] = data_pd.index
          yearM2 = year+'/'+Name + '.csv'
          data_pd.to_csv(yearM2)
    return data_pd


output = hdf_to_dataframe('GLDAS_CLSM10_M.A200001.021.hdf')

ACond_tavg

In [10]:
output

,lon,A200001ACond_tavg,A200001Albedo_inst,A200001AvgSurfT_inst,A200001CanopInt_inst,A200001ECanop_tavg,A200001ESoil_tavg,A200001Evap_tavg,A200001LWdown_f_tavg,A200001Lwnet_tavg,...,A200001SoilTMP10_29cm_inst,A200001SoilTMP144_295cm_inst,A200001SoilTMP295_1295cm_inst,A200001SoilTMP29_68cm_inst,A200001SoilTMP68_144cm_inst,A200001Swnet_tavg,A200001TVeg_tavg,A200001TWS_inst,A200001Tair_f_inst,A200001Wind_f_inst
/lat,,,,,,,,,,,,,,,,,,,,,
-59.5,-179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
-58.5,-179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
-57.5,-179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
-56.5,-179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
-55.5,-179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85.5,179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
86.5,179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
87.5,179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
88.5,179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
89.5,179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0

# Function to iterate through all files and append them in one DataFrame

In [ ]:
def gldas_year_mean_to_csv(year):
    try:
        import pandas as pd 
        import h5py
        import numpy as np
        import os
        import tables
    except:
        print("Missing Library")
    
    year = str(year)
    list2 = []
    j = 0
    for i in range(1,13):
        if i < 10:
            yearM = year +str(j)+ str(i)
        else:
            yearM = year + str(i)
        path = 'gldas/GLDAS_CLSM10_M.'+'A'+yearM+'.021.hdf'
        list2.append(path)
    print(list2)
    gldas_combined = pd.DataFrame()
    os.mkdir(year)
    csv = 1
    for name in list2:
        data_I = hdf_to_dataframe(name,year,csv)

In [ ]:
for j in range(2019,2021):
    gldas_year_mean_to_csv(j)

In [ ]:
def month_csv_to_year_csv(year):
    from os import listdir
    print("Current working directory: {0}".format(os.getcwd()))
    path = 'D:\\MDA\\GLDAS_'+str(year)
    try:
        os.chdir(path)
        print("Current working directory: {0}".format(os.getcwd()))
    except FileNotFoundError:
        print("Directory: {0} does not exist".format(path))
    except NotADirectoryError:
        print("{0} is not a directory".format(path))
    except PermissionError:
        print("You do not have permissions to change to {0}".format(path))
    filepaths = [f for f in listdir("./") if f.endswith('.csv')]
    df = pd.concat(map(pd.read_csv, filepaths)).groupby(['lon','lat']).mean()
    filename = "GLDAS_year_mean_"+str(year)+".csv"
    df.to_csv(filename)
    
for j in range(2000,2014):
    month_csv_to_year_csv(j)

In [ ]:
from os import listdir
print("Current working directory: {0}".format(os.getcwd()))
path = 'D:\\MDA\\GLDAS_year_mean_2000_2013'
try:
   os.chdir(path)
   print("Current working directory: {0}".format(os.getcwd()))
except FileNotFoundError:
   print("Directory: {0} does not exist".format(path))
except NotADirectoryError:
   print("{0} is not a directory".format(path))
except PermissionError:
   print("You do not have permissions to change to {0}".format(path))
filepaths = [f for f in listdir("./") if f.endswith('.csv')]
df = pd.concat(map(pd.read_csv, filepaths), axis=1, join="inner"))
df.to_csv("GLDAS_2000_2013_yearly.csv")